# Generated by Django 3.0.5 on 2020-04-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernels',
            name='comment_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
