# Generated by Django 3.0.5 on 2020-04-03 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_kernels_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasets',
            name='most_recent_disc',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasets',
            name='most_recent_kernel',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
