# Generated by Django 3.0.5 on 2020-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_datasets_most_recent_kernel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_name', models.TextField()),
                ('dat_url', models.CharField(max_length=500, unique=True)),
                ('last_updated', models.DateTimeField()),
                ('users', models.ManyToManyField(to='events.Users')),
            ],
        ),
    ]
